### ISSUE TITLE
Feature request: REST API

### ISSUE THREAD

**Issue by amacado** [AlphaNodes/additional_tags#21]
Any plans on providing a REST API to manage (add/remove on issues/pages) TAGs programmatically?

Redmine Core REST API: [redmine.org/projects/redmine/wiki/rest_api](https://www.redmine.org/projects/redmine/wiki/rest_api)

**Comment by alexandermeindl** [comment]
Hi @amacado,

This is already implemented, but documentation is missing. See https://github.com/AlphaNodes/additional_tags/blob/main/test/integration/api_test/issues_test.rb#L55 for examples.

By writing tests a couple of hours ago, I found a bug on creating new issues with tags - this should be fixed with my last commit.

**Comment by sk2andy** [comment]
not showing up for me when I run `http://localhost:3000/issues.json` but when I run `http://localhost:3000/issues/1.json` Maybe worth a consideration?
