### ISSUE TITLE
Enhancement Request: Separate Tag Creation from ability to Add an existing Tag to an Issue

### ISSUE THREAD

**Issue by GaryAitken** [alphanodes/additional_tags#51]
It would be useful to be able to limit the creation of a new tag to a particular role, while still allowing others to add any of the existing tags to an issue.  Currently, AFAIK the Add permission allows both the creation of a new tag and adding a tag to an issue.

**Comment by shiningwild** [comment]
Hello @GaryAitken ,

If I understand you correctly, this is already how it works. 
There are three permissions available: 
Add issue tags = Allows the user to create new Tags
Edit issue tags = Allows the user to change Tags for an issue (Add/Remove Existing Tags)
Display issue tags = Allows the user to see the Tags for an issue

I did a test. I turned off "Add Issue tags" and enabled "Edit Issue tags." 
I tried creating a new tag and it did not work, but I was able to add an existing Tag to an issue. 

Funny tidbit: 
Enabling "Add issue tags" and disabling "Edit issue tags" is a funny combination because the user cannot access the tags for an issue.

**Comment by GaryAitken** [comment]
My appologies.  I had the add permission on in one role and off in another and the user has both roles.
As a side note, when editing an issue, if you do not have the add permission, you can add a tag in the tag line and when you hit <enter> or a comma, it looks like it worked -- the tag appears with an 'X' beside it; but it disappears when doing a save, with no warning / error given.  It would be nice if an error was displayed and the tag add process could not be completed.

**Comment by alexandermeindl** [comment]
As I understood, this problem was a permission issue and is solved.
